version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - godot
    - lll
    - nilnil
    - noinlineerr
    - tagliatelle
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
    funlen:
      lines: 120
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo